# Default values for demoservice1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
chartVersion: "1.0"
appversion: 10
build : "1"
image:
  repository: codefresh-course/demochat
  tag: master
  pullPolicy: Always
service:
  name: demochat
  type: LoadBalancer
  externalPort: 80
  internalPort: 5000
commit:
  sha: "i1234"
  branch: "master"
  repo : "codefresh-course/demochat"
